// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDB56fbORVgaHTXlNqp5CYjLr-GgYy9ZrQ',
    appId: '1:1038441739372:web:b49a5e4b3588d243931449',
    messagingSenderId: '1038441739372',
    projectId: 'flutterlab2-7c8a0',
    authDomain: 'flutterlab2-7c8a0.firebaseapp.com',
    storageBucket: 'flutterlab2-7c8a0.firebasestorage.app',
    measurementId: 'G-VJZN8RJE8T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5mPA4IougCVx0b2IJ4TfMI6PlTWrpH64',
    appId: '1:1038441739372:android:1b62728fc7eedac7931449',
    messagingSenderId: '1038441739372',
    projectId: 'flutterlab2-7c8a0',
    storageBucket: 'flutterlab2-7c8a0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxo45UQREEEvbQaHFD-JDFAIpEY4ZL_BU',
    appId: '1:1038441739372:ios:575cdf7fc81134b2931449',
    messagingSenderId: '1038441739372',
    projectId: 'flutterlab2-7c8a0',
    storageBucket: 'flutterlab2-7c8a0.firebasestorage.app',
    iosClientId: '1038441739372-c4i1usehopslsajle0lppjiiog6tf4n6.apps.googleusercontent.com',
    iosBundleId: 'com.example.lab1UiLogin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBxo45UQREEEvbQaHFD-JDFAIpEY4ZL_BU',
    appId: '1:1038441739372:ios:575cdf7fc81134b2931449',
    messagingSenderId: '1038441739372',
    projectId: 'flutterlab2-7c8a0',
    storageBucket: 'flutterlab2-7c8a0.firebasestorage.app',
    iosClientId: '1038441739372-c4i1usehopslsajle0lppjiiog6tf4n6.apps.googleusercontent.com',
    iosBundleId: 'com.example.lab1UiLogin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDB56fbORVgaHTXlNqp5CYjLr-GgYy9ZrQ',
    appId: '1:1038441739372:web:6c39c1c277d6830a931449',
    messagingSenderId: '1038441739372',
    projectId: 'flutterlab2-7c8a0',
    authDomain: 'flutterlab2-7c8a0.firebaseapp.com',
    storageBucket: 'flutterlab2-7c8a0.firebasestorage.app',
    measurementId: 'G-H9P6D7YR2H',
  );
}
